name: Container Scanner
on: [push]

jobs:
  build:
    name: Composition Analysis
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Image
        run: |
          docker build -f $GITHUB_WORKSPACE/dockerfile -t test:${{ github.sha }} . 

      - name: Execute Test
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test:${{ github.sha }}'
          format: 'table'
          ignore-unfixed: true
          exit-code: '1'
          severity: 'CRITICAL'
