name: Regression Suite
on: [push]

jobs:
  regression_tests:
    name: Regression Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set Up Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel
          pip install --upgrade pytest coverage
          pip install -r $GITHUB_WORKSPACE/requirements.txt
          pip install -r $GITHUB_WORKSPACE/tests/requirements.txt

      - name: Start GCS Emulator
        run: |
          docker run -d --name fake-gcs-server \
                     -p 9090:4443 \
                     fsouza/fake-gcs-server -scheme http

      - name: Run Regression Tests
        run: coverage run -m pytest

      - name: Check Coverage
        run: coverage report --include=src* --fail-under=80 -m

  mypy:
    name: Type Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set Up Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
          
      - name: Install Requirements
        run:  pip install mypy

      - name: Execute Test
        run: mypy src
