name: Static Analysis
on: [push]

jobs:
  test:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set Up Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 
          
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade bandit

      - name: Execute Test
        run: bandit -r src
